// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjvughwlstknjkykdfzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqdnVnaHdsc3RrbmpreWtkZnpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDY3NTcsImV4cCI6MjA2MDEyMjc1N30.vhHFvT-CGfo5MtZxSj6yAPuFUIkfu6Njp1PjRisQT6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);